spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc: jdbc:mysql://localhost:3306
    username: guyujung
    password: 1234

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh